### ISSUE TITLE
Targeting html in CSS

### ISSUE THREAD

**Issue by griffinlacek** [tomtaborsky/f1-3-c2p1-colmar-academy#4]
Nothing wrong with using html to set font-family for the page, but body is often used instead as it directly influences children elements. Here's a good discussion on this: https://css-tricks.com/html-vs-body-in-css/

https://github.com/tomtaborsky/f1-3-c2p1-colmar-academy/blob/master/ColmarSchool/resources/css/index.css#L2-L5

**Comment by tomtaborsky** [comment]
thanks for that input
