### ISSUE TITLE
SUMMARY

### ISSUE THREAD

**Issue by griffinlacek** [tomtaborsky/f1-3-c2p1-colmar-academy#6]
**Grade:** Exceeds Expectations

**Summary:** This project is good! It meets the spec and the code is clean and free of errors. Only area of improvement to note is to consider looking into changing class/id names to follow camelCase or -/_ naming conventions

As a challenge, a great exercise would be expanding the site with links to the other pages, making minor style tweaks to these pages (the importance here is just getting to practice building multi-page sites). This will give you experience with building and managing a multi-page website.

Good work!

**Comment by tomtaborsky** [comment]
Thank you Griffin!

I will take this into account and further work on my skills.
thanks for taking the time for this review.

Cheers,
Tom
